---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: gke-example-configmap
    envs:
      - configmap.properties

secretGenerator:
  - name: gke-example-secret
    envs:
      - secret.properties
