---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: mck-b2b-connect-docker.jfrog.io/b2b-connect/gke-example
    newTag: 0.0.0

commonLabels:
  app: gke-example

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: gke-example-configmap-common
    envs:
      - configmap.properties

secretGenerator:
  - name: gke-example-secret-common
    envs:
      - secret.properties
